package com.aircell.acpu.messaging;

public enum AbsServiceStatusCode {
	ABS_SERVICE_INITIALIZING,
	ABS_SERVICE_AVAILABLE,
	ABS_SERVICE_BLOCKED_BY_NOC,
	ABS_SERVICE_UNAVAILABLE_GATE,
	ABS_SERVICE_UNAVAILABLE_BELOW_SERVICE_ALTITUDE,
	ABS_SERVICE_UNAVAILABLE_GROUND,
	ABS_SERVICE_UNAVAILABLE_AIRBORNE,
	ABS_SERVICE_UNAVAILABLE,
	UNKNOWN_ABS_SERVICE_STATE
}
