package com.aircell.acpu.messaging;

public enum AcpuErrorCode {
	ACPU_SERVER_ERROR,
	ACPU_SERVER_NOT_OPERATIONAL,
	ACPU_COMPONENT_DOWN,
	ACPU_SERVER_SHUTDOWN_IN_PROGRESS,
	ACPU_FIREWALL_UPDATE_ERROR,
	ACPU_FIREWALL_NOT_RESPONDING,
	UNKNOWN_ACPU_SERVER_ERROR,

	ACPU_EXTERNAL_STATE_ERROR,
	ATG_LINK_DOWN,
	OUT_OF_COVERAGE_AREA,
	UNKNOWN_ACPU_EXTERNAL_STATE_ERROR,

	RADIUS_SERVER_ERROR,
	AUTHENTICATION_REJECTED,
	RADIUS_SERVER_NOT_REACHABLE,
	INCORRECT_RADIUS_SHARED_SECRET,
	SUBSCRIPTION_REJECTED,
	UNKNOWN_RADIUS_SERVER_ERROR,

	ACPU_CLIENT_ERORR,
	UNASSIGNED_CLIENT_IP_ADDRESS,
	UNKNOWN_ACPU_CLIENT_ERORR
}
