package com.aircell.acpu.messaging;

public enum AtgLinkStatusCode {
	ATG_LINK_UP,
	ATG_LINK_FAILURE,
	ATG_LINK_STRENGTH_LOW,
	ATG_OUT_OF_COVERAGE_AREA,
	ATG_LINK_STRENGTH_UNKNOWN,
	UNKNOWN_ATG_LINK_STATE
}
