package com.aircell.acpu.messaging;

public enum SessionStatusCode {
	USER_NOT_AUTHENTICATED,
	USER_AUTHENTICATED,
	USER_SUBSCRIBED,
	USER_UNSUBSCRIBED,
	USER_FORCIBLY_LOGGED_OFF,
	ABS_SERVICE_UNAVAILABLE,
	UNKNOWN_USER_STATE
}
